/*  OptiVec.h

  object-oriented interface for OptiVec vector functions

  Copyright (c) 1996-2002 by OptiCode
  All Rights Reserved.
*/

#ifndef __OPTIVEC_H
#define __OPTIVEC_H

#include <VecAll.h>
#include <MatAll.h>
#include <biVecObj.h>
#include <siVecObj.h>
#include <iVecObj.h>
#include <liVecObj.h>
#include <qiVecObj.h>
#include <ubVecObj.h>
#include <usVecObj.h>
#include <uVecObj.h>
#include <ulVecObj.h>
#include <uiVecObj.h>
#include <VecObj.h>
#include <fVecObj.h>
#include <dVecObj.h>
#include <eVecObj.h>
#include <cfVecObj.h>
#include <cdVecObj.h>
#include <ceVecObj.h>
#include <pfVecObj.h>
#include <pdVecObj.h>
#include <peVecObj.h>

#endif  /* __OPTIVEC_H */
